// flow-typed signature: 71990992698ff7078349c6e316268d35
// flow-typed version: <<STUB>>/@optimizely/optimizely-sdk_v^2.3.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@optimizely/optimizely-sdk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@optimizely/optimizely-sdk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@optimizely/optimizely-sdk/dist/optimizely.browser.umd' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/dist/optimizely.browser.umd.min' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/core/audience_evaluator/index' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/core/audience_evaluator/index.tests' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/core/bucketer/index' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/core/bucketer/index.tests' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/core/condition_evaluator/index' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/core/condition_evaluator/index.tests' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/core/decision_service/index' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/core/decision_service/index.tests' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/core/event_builder/index' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/core/event_builder/index.tests' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/core/notification_center/index' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/core/project_config/index' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/core/project_config/index.tests' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/index.browser' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/index.browser.tests' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/index.node' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/index.node.tests' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/optimizely/index' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/optimizely/index.tests' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/optimizely/project_config_schema' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/plugins/error_handler/index' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/plugins/error_handler/index.tests' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/plugins/event_dispatcher/index.browser' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/plugins/event_dispatcher/index.browser.tests' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/plugins/event_dispatcher/index.node' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/plugins/event_dispatcher/index.node.tests' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/plugins/logger/enums' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/plugins/logger/index' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/plugins/logger/index.tests' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/tests/test_data' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/utils/attributes_validator/index' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/utils/attributes_validator/index.tests' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/utils/config_validator/index' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/utils/config_validator/index.tests' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/utils/enums/index' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/utils/event_tag_utils/index' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/utils/event_tag_utils/index.tests' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/utils/event_tags_validator/index' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/utils/event_tags_validator/index.tests' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/utils/fns/index' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/utils/json_schema_validator/index' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/utils/json_schema_validator/index.tests' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/utils/string_value_validator/index' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/utils/string_value_validator/index.tests' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/utils/user_profile_service_validator/index' {
  declare module.exports: any;
}

declare module '@optimizely/optimizely-sdk/lib/utils/user_profile_service_validator/index.tests' {
  declare module.exports: any;
}

// Filename aliases
declare module '@optimizely/optimizely-sdk/dist/optimizely.browser.umd.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/dist/optimizely.browser.umd'>;
}
declare module '@optimizely/optimizely-sdk/dist/optimizely.browser.umd.min.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/dist/optimizely.browser.umd.min'>;
}
declare module '@optimizely/optimizely-sdk/lib/core/audience_evaluator/index.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/core/audience_evaluator/index'>;
}
declare module '@optimizely/optimizely-sdk/lib/core/audience_evaluator/index.tests.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/core/audience_evaluator/index.tests'>;
}
declare module '@optimizely/optimizely-sdk/lib/core/bucketer/index.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/core/bucketer/index'>;
}
declare module '@optimizely/optimizely-sdk/lib/core/bucketer/index.tests.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/core/bucketer/index.tests'>;
}
declare module '@optimizely/optimizely-sdk/lib/core/condition_evaluator/index.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/core/condition_evaluator/index'>;
}
declare module '@optimizely/optimizely-sdk/lib/core/condition_evaluator/index.tests.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/core/condition_evaluator/index.tests'>;
}
declare module '@optimizely/optimizely-sdk/lib/core/decision_service/index.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/core/decision_service/index'>;
}
declare module '@optimizely/optimizely-sdk/lib/core/decision_service/index.tests.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/core/decision_service/index.tests'>;
}
declare module '@optimizely/optimizely-sdk/lib/core/event_builder/index.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/core/event_builder/index'>;
}
declare module '@optimizely/optimizely-sdk/lib/core/event_builder/index.tests.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/core/event_builder/index.tests'>;
}
declare module '@optimizely/optimizely-sdk/lib/core/notification_center/index.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/core/notification_center/index'>;
}
declare module '@optimizely/optimizely-sdk/lib/core/project_config/index.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/core/project_config/index'>;
}
declare module '@optimizely/optimizely-sdk/lib/core/project_config/index.tests.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/core/project_config/index.tests'>;
}
declare module '@optimizely/optimizely-sdk/lib/index.browser.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/index.browser'>;
}
declare module '@optimizely/optimizely-sdk/lib/index.browser.tests.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/index.browser.tests'>;
}
declare module '@optimizely/optimizely-sdk/lib/index.node.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/index.node'>;
}
declare module '@optimizely/optimizely-sdk/lib/index.node.tests.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/index.node.tests'>;
}
declare module '@optimizely/optimizely-sdk/lib/optimizely/index.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/optimizely/index'>;
}
declare module '@optimizely/optimizely-sdk/lib/optimizely/index.tests.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/optimizely/index.tests'>;
}
declare module '@optimizely/optimizely-sdk/lib/optimizely/project_config_schema.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/optimizely/project_config_schema'>;
}
declare module '@optimizely/optimizely-sdk/lib/plugins/error_handler/index.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/plugins/error_handler/index'>;
}
declare module '@optimizely/optimizely-sdk/lib/plugins/error_handler/index.tests.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/plugins/error_handler/index.tests'>;
}
declare module '@optimizely/optimizely-sdk/lib/plugins/event_dispatcher/index.browser.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/plugins/event_dispatcher/index.browser'>;
}
declare module '@optimizely/optimizely-sdk/lib/plugins/event_dispatcher/index.browser.tests.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/plugins/event_dispatcher/index.browser.tests'>;
}
declare module '@optimizely/optimizely-sdk/lib/plugins/event_dispatcher/index.node.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/plugins/event_dispatcher/index.node'>;
}
declare module '@optimizely/optimizely-sdk/lib/plugins/event_dispatcher/index.node.tests.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/plugins/event_dispatcher/index.node.tests'>;
}
declare module '@optimizely/optimizely-sdk/lib/plugins/logger/enums.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/plugins/logger/enums'>;
}
declare module '@optimizely/optimizely-sdk/lib/plugins/logger/index.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/plugins/logger/index'>;
}
declare module '@optimizely/optimizely-sdk/lib/plugins/logger/index.tests.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/plugins/logger/index.tests'>;
}
declare module '@optimizely/optimizely-sdk/lib/tests/test_data.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/tests/test_data'>;
}
declare module '@optimizely/optimizely-sdk/lib/utils/attributes_validator/index.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/utils/attributes_validator/index'>;
}
declare module '@optimizely/optimizely-sdk/lib/utils/attributes_validator/index.tests.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/utils/attributes_validator/index.tests'>;
}
declare module '@optimizely/optimizely-sdk/lib/utils/config_validator/index.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/utils/config_validator/index'>;
}
declare module '@optimizely/optimizely-sdk/lib/utils/config_validator/index.tests.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/utils/config_validator/index.tests'>;
}
declare module '@optimizely/optimizely-sdk/lib/utils/enums/index.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/utils/enums/index'>;
}
declare module '@optimizely/optimizely-sdk/lib/utils/event_tag_utils/index.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/utils/event_tag_utils/index'>;
}
declare module '@optimizely/optimizely-sdk/lib/utils/event_tag_utils/index.tests.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/utils/event_tag_utils/index.tests'>;
}
declare module '@optimizely/optimizely-sdk/lib/utils/event_tags_validator/index.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/utils/event_tags_validator/index'>;
}
declare module '@optimizely/optimizely-sdk/lib/utils/event_tags_validator/index.tests.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/utils/event_tags_validator/index.tests'>;
}
declare module '@optimizely/optimizely-sdk/lib/utils/fns/index.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/utils/fns/index'>;
}
declare module '@optimizely/optimizely-sdk/lib/utils/json_schema_validator/index.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/utils/json_schema_validator/index'>;
}
declare module '@optimizely/optimizely-sdk/lib/utils/json_schema_validator/index.tests.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/utils/json_schema_validator/index.tests'>;
}
declare module '@optimizely/optimizely-sdk/lib/utils/string_value_validator/index.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/utils/string_value_validator/index'>;
}
declare module '@optimizely/optimizely-sdk/lib/utils/string_value_validator/index.tests.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/utils/string_value_validator/index.tests'>;
}
declare module '@optimizely/optimizely-sdk/lib/utils/user_profile_service_validator/index.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/utils/user_profile_service_validator/index'>;
}
declare module '@optimizely/optimizely-sdk/lib/utils/user_profile_service_validator/index.tests.js' {
  declare module.exports: $Exports<'@optimizely/optimizely-sdk/lib/utils/user_profile_service_validator/index.tests'>;
}
