name: Main
on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack before setting up Node
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.8.0'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build all packages
        run: yarn workspaces foreach -A run build

      - name: Test all packages
        run: yarn workspaces foreach -A run test
